name: CI - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]   # Runs only when code is pushed to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (modern Docker builder)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Docker Hub (using GitHub secrets)
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: waseem011/health-webapp:latest

